### PR TITLE
Clion instructions

### PR DESCRIPTION
**Pull request by ryanz34**
Clion instructions for remote debug

### CODE REVIEW

**Comment by deandrebaker** [comment]
@ryanz34 are you confident that this uses the g++ compiler on the ece ubuntu server instead of the cmake compiler locally?

**Comment by ryanz34** [comment]
It will use CMake on ece ubuntu and run the program there. Someone with Clion should go through the steps and verify I didn't miss anything and that the instructions are clear(pretty sure I didn't miss anything).

**Comment by deandrebaker** [comment]
@ryanz34 okay I'll get someone I know to try it out. The only thing I'm worried about is that if using cmake doesn't use the g++ compiler like the prof wants us to. I'll get the person trying this guide out to verify whether this is true or not. Thank you so much for this documentation!

**Comment by ryanz34** [comment]
I think CMake might use the system compiler c++ on eceUbuntu. I'll draft this PR for now and add some instructions to change it to use g++ later.

**Pull request merged**
